// <auto-generated />
using LightboxBackend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LightboxBackend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260112190413_AddMissingFields")]
    partial class AddMissingFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("LightboxBackend.Models.LedSpacingOption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Cm")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("LedSpacingOptions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cm = 10
                        },
                        new
                        {
                            Id = 2,
                            Cm = 15
                        });
                });

            modelBuilder.Entity("LightboxBackend.Models.SystemSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AdapterPricesJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("DigerBaskiM2")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("DigerKoseAparatiAdet")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("DigerSabitEkstraGider")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Kasa10Double")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Kasa10Single")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Kasa12Double")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Kasa12Single")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Kasa4Single")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Kasa5Single")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Kasa8Double")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Kasa8Single")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("LedDisMekan")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("LedIcMekan")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ZeminDekota4mm")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ZeminKompozit4mm")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ZeminMdf4mm")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Settings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AdapterPricesJson = "[{\"amps\":3,\"price\":50,\"watt\":36},{\"amps\":5,\"price\":80,\"watt\":60},{\"amps\":10,\"price\":150,\"watt\":120},{\"amps\":12.5,\"price\":180,\"watt\":150},{\"amps\":20,\"price\":250,\"watt\":240},{\"amps\":30,\"price\":350,\"watt\":360}]",
                            DigerBaskiM2 = 300m,
                            DigerKoseAparatiAdet = 50m,
                            DigerSabitEkstraGider = 40m,
                            Kasa10Double = 1000m,
                            Kasa10Single = 500m,
                            Kasa12Double = 1500m,
                            Kasa12Single = 750m,
                            Kasa4Single = 150m,
                            Kasa5Single = 250m,
                            Kasa8Double = 600m,
                            Kasa8Single = 400m,
                            LedDisMekan = 4m,
                            LedIcMekan = 2m,
                            ZeminDekota4mm = 500m,
                            ZeminKompozit4mm = 600m,
                            ZeminMdf4mm = 200m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
