// <auto-generated />
using System;
using LightboxBackend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LightboxBackend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260121223805_AddPricingTables")]
    partial class AddPricingTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("LightboxBackend.Models.AdapterPrice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amperage")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Wattage")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AdapterPrices");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amperage = 3m,
                            Name = "3A Adaptör",
                            Price = 7.60m,
                            Wattage = 36m
                        },
                        new
                        {
                            Id = 2,
                            Amperage = 5m,
                            Name = "5A Adaptör",
                            Price = 9.40m,
                            Wattage = 60m
                        },
                        new
                        {
                            Id = 3,
                            Amperage = 10m,
                            Name = "10A Adaptör",
                            Price = 13.20m,
                            Wattage = 120m
                        },
                        new
                        {
                            Id = 4,
                            Amperage = 12.5m,
                            Name = "12.5A Adaptör",
                            Price = 15.40m,
                            Wattage = 150m
                        },
                        new
                        {
                            Id = 5,
                            Amperage = 16.5m,
                            Name = "16.5A Adaptör",
                            Price = 21.00m,
                            Wattage = 198m
                        },
                        new
                        {
                            Id = 6,
                            Amperage = 20m,
                            Name = "20A Adaptör",
                            Price = 22.80m,
                            Wattage = 240m
                        },
                        new
                        {
                            Id = 7,
                            Amperage = 30m,
                            Name = "30A Adaptör",
                            Price = 25.20m,
                            Wattage = 360m
                        });
                });

            modelBuilder.Entity("LightboxBackend.Models.BackingCost", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MaterialType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PricePerM2")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("BackingCosts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayName = "3 MM MDF",
                            MaterialType = "MDF_3MM",
                            PricePerM2 = 4.00m
                        },
                        new
                        {
                            Id = 2,
                            DisplayName = "5 MM MDF",
                            MaterialType = "MDF_5MM",
                            PricePerM2 = 6.50m
                        },
                        new
                        {
                            Id = 3,
                            DisplayName = "4.5 MM DEKOTA",
                            MaterialType = "DEKOTA_4_5MM",
                            PricePerM2 = 6.00m
                        },
                        new
                        {
                            Id = 4,
                            DisplayName = "KOMPOZİT",
                            MaterialType = "KOMPOZIT_4MM",
                            PricePerM2 = 15.00m
                        });
                });

            modelBuilder.Entity("LightboxBackend.Models.LedSpacingOption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Cm")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("LedSpacingOptions");
                });

            modelBuilder.Entity("LightboxBackend.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConfigurationDetails")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomerEmail")
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomerName")
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomerPhone")
                        .HasColumnType("TEXT");

                    b.Property<string>("Dimensions")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("LightboxBackend.Models.ProfileCost", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("DepthCm")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDoubleSided")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PricePerMeter")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ProfileCosts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DepthCm = 4.5m,
                            IsDoubleSided = false,
                            Name = "4.5cm Tek Taraf",
                            PricePerMeter = 4.30m
                        },
                        new
                        {
                            Id = 2,
                            DepthCm = 8m,
                            IsDoubleSided = false,
                            Name = "8cm Tek Taraf",
                            PricePerMeter = 5.00m
                        },
                        new
                        {
                            Id = 3,
                            DepthCm = 10m,
                            IsDoubleSided = false,
                            Name = "10cm Tek Taraf",
                            PricePerMeter = 6.00m
                        },
                        new
                        {
                            Id = 4,
                            DepthCm = 12m,
                            IsDoubleSided = false,
                            Name = "12cm Tek Taraf",
                            PricePerMeter = 7.50m
                        },
                        new
                        {
                            Id = 5,
                            DepthCm = 8m,
                            IsDoubleSided = true,
                            Name = "8cm Çift Taraf",
                            PricePerMeter = 6.00m
                        },
                        new
                        {
                            Id = 6,
                            DepthCm = 10m,
                            IsDoubleSided = true,
                            Name = "10cm Çift Taraf",
                            PricePerMeter = 10.00m
                        },
                        new
                        {
                            Id = 7,
                            DepthCm = 12m,
                            IsDoubleSided = true,
                            Name = "12cm Çift Taraf",
                            PricePerMeter = 15.00m
                        });
                });

            modelBuilder.Entity("LightboxBackend.Models.SystemSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AdapterPricesJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("AmperesPerMeter")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CableFixedCost")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CornerPiecePrice")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("LaborRatePercentage")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("LedIndoorPricePerMeter")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("LedOutdoorPricePerMeter")
                        .HasColumnType("TEXT");

                    b.Property<string>("LedSpacingOptionsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PrintCostPerM2")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProfileCostsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ProfitMarginPercentage")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Settings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AdapterPricesJson = "[]",
                            AmperesPerMeter = 1.0m,
                            CableFixedCost = 6.00m,
                            CornerPiecePrice = 0.70m,
                            LaborRatePercentage = 30.0m,
                            LedIndoorPricePerMeter = 2.00m,
                            LedOutdoorPricePerMeter = 3.00m,
                            LedSpacingOptionsJson = "[15]",
                            PrintCostPerM2 = 10.00m,
                            ProfileCostsJson = "[]",
                            ProfitMarginPercentage = 30.0m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
